app = "linebot-admin-chat"
primary_region = "sin"

[build]

[env]
  HOST = "0.0.0.0"
  PORT = "8000"
  ENVIRONMENT = "production"
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "data"
  destination = "/app/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
